management:
  endpoint:
    metrics:
      enabled: true
  tracing:
    enabled: true
    sampling.probability: 1.0
    propagation:
      type: b3
    baggage:
      correlation:
        enabled: true
        fields:
          - contextDataName
      remote-fields:
        - contextDataName
logging.level.io.micrometer.tracing: TRACE